main: main.cpp canonical.cpp find.cpp checkPercolation.cpp conversion.cpp aggregate.cpp entropy.cpp avg.cpp
	g++ -o wopb150 main.cpp canonical.cpp find.cpp checkPercolation.cpp conversion.cpp aggregate.cpp entropy.cpp avg.cpp -I.
